# Generated by Django 3.1 on 2020-10-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlogdata', '0003_auto_20201018_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='UserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='rlogdata.usr_table'),
        ),
    ]
