# Generated by Django 3.1 on 2020-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlogdata', '0004_auto_20201018_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staging',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
