# Generated by Django 3.1 on 2020-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_ID', models.CharField(max_length=50)),
                ('Company_Name', models.TextField(max_length=200)),
                ('Job_Category', models.CharField(max_length=100)),
                ('Job_Sub_Category', models.CharField(default='', max_length=100)),
                ('HR_Name', models.TextField(max_length=100)),
                ('Job_Role', models.CharField(default='', max_length=3000)),
                ('Skills_Required', models.CharField(default='', max_length=3000, null=True)),
                ('Creation_Date', models.DateField()),
                ('End_Date', models.DateField(default='')),
                ('Number_of_openings', models.IntegerField()),
                ('Jopb_Location', models.CharField(max_length=300)),
                ('Designation_of_job', models.CharField(default='', max_length=200)),
                ('ctc', models.IntegerField()),
                ('Min_Exp', models.IntegerField()),
                ('Max_Exp', models.IntegerField()),
                ('CompanyID', models.CharField(max_length=50)),
            ],
        ),
    ]
