# Generated by Django 3.1 on 2020-08-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200828_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandate',
            name='Designation_of_job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
